- README.md
This PR adds explanations of some of the points that beginner might stumble on. By the way, my English is so rough, so there may be a lot of room for correct and/or improve. Please feel free to correct and improve it.
> Add the usage section to README.md

- .github/workflows/workflow.yml
> Detect uncommitted changes to the lib directory

- lib/install-ocaml-windows.cmd
- src/install-ocaml-windows.cmd
> Add Cygwin setup to known location (usable by later GHA steps)

- CHANGELOG.md
- dist/install-ocaml-unix.sh
- src/install-ocaml-unix.sh
> Correctly activate Unix switches

- .github/workflows/workflow.yml
- CHANGELOG.md
- README.md
- action.yml
- examples.md
- src/constants.ts
- src/depext.ts
- src/dune.ts
- src/installer.ts
> Revert "Remove usage of opam depext plugin"

- CHANGELOG.md
- package.json
If everything is fine, merge and ship on 6th.
> Prepare v2.0.0-beta4

- CHANGELOG.md
- src/installer.ts
- src/opam.ts
Partially address #299.
Related PR: https://github.com/ocaml-opam/opam-depext/pull/142
> Unlock opam 2.1 on the Ubuntu and macOS runners

- lint-fmt/index.js
- src/setup-ocaml/cache.ts
> Better error handling on saving the cache

- CHANGELOG.md
- src/setup-ocaml/opam.ts
> Ensure opam release assets exist

- CHANGELOG.md
- src/setup-ocaml/opam.ts
> Update the package index if the system package installation fails

- dist/install-ocaml-windows.sh
- src/install-ocaml-windows.sh
> Turn off git directory ownership check [1.x version]

- CHANGELOG.md
- src/setup-ocaml/cache.ts
- src/setup-ocaml/constants.ts
- src/setup-ocaml/opam.ts
Related issue: https://github.com/fdopen/opam-repository-mingw/issues/108
> Set the upstream git url as a secondary repository on Windows

- CHANGELOG.md
- src/setup-ocaml/cache.ts
> uses opam-disable-sandboxing for opam cache key computation

- .gitattributes
- package.json
- packages/eslint-config-ocaml/tsconfig.json
- packages/lint-doc/package.json
- packages/lint-doc/tsconfig.json
- packages/lint-fmt/package.json
- packages/lint-fmt/tsconfig.json
- packages/lint-opam/package.json
- packages/lint-opam/tsconfig.json
- packages/setup-ocaml/package.json
- packages/setup-ocaml/src/cache.ts
- packages/setup-ocaml/tsconfig.json
- yarn.lock
The state of the action has been pretty stable lately, and blowing the cache with each patch version seems a bit silly.
> Remove the action version from the cache key

- CHANGELOG.md
- packages/setup-ocaml/src/installer.ts
Ref: https://github.com/ocaml/opam/pull/5686
> Prevent opam bug by leaving verbose mode undefined

- .github/workflows/workflow.yml
- CHANGELOG.md
- action.yml
- dist/post/LICENSE.txt
- packages/setup-ocaml/src/cache.ts
- packages/setup-ocaml/src/constants.ts
- packages/setup-ocaml/src/opam.ts
Closes: https://github.com/ocaml/setup-ocaml/issues/698
> Add support to allow pre-release opam

- CONTRIBUTING.md
~The content of this file is currently not accurate. It does not work for me. See #794~ EDIT: works now.
> Add a basic CONTRIBUTING.md file

- CHANGELOG.md
- dist/index.js
- packages/setup-ocaml/src/installer.ts
Ref
- https://github.com/ocaml/Zarith/pull/153
- https://github.com/ocsigen/js_of_ocaml/pull/1616
> Always set-up Cygwin whether or not the cache is hit

- CHANGELOG.md
- packages/setup-ocaml/src/windows.ts
> Configure git config globally instead of locally

- CHANGELOG.md
- packages/setup-ocaml/src/unix.ts
Just a quick fix. Better fixes will come later.
> Fix darcs installation failure on latest Ubuntu image

- packages/setup-ocaml/src/opam.ts
https://github.com/ocaml/opam/releases/tag/2.3.0
> Unlock opam 2.3

- packages/setup-ocaml/src/opam.ts
- packages/setup-ocaml/src/unix.ts
> Revert "Run `opam update --depext` before installing system dependencies"
