ocaml/setup-ocaml

action.yml

Along the same lines as the description. An alternative would be "OCaml Setup." See https://grammarist.com/spelling/set-up-vs-setup/.

Fix action name

---

lib/index.js
src/setup-ocaml.ts

Strings are thrown inside `install.ts`, so when they're getting caught, `error.message` is undefined. Using `error.toString()` instead, which will do nothing on string and print something anyway with exceptions
Also, npm advised to update the dependencies (using npm audit fix) so that's what I did, but I can revert the commit if you prefer :)

Fix some dependency vulnerability + setFailed message

---

README.md
__tests__/installer.test.ts
action.yml
lib/index.js
lib/install-ocaml-windows.cmd
lib/install-ocaml-windows.sh
src/install-ocaml-windows.cmd
src/install-ocaml-windows.sh
src/installer.ts
src/setup-ocaml.ts

When setting up github actions for [xen-api](https://github.com/xapi-project/xen-api/pull/4139) a post-install action to change the default repository was needed. This is because the default opam repository cannot be used to fetch its dependencies.
This PR adds a parameter to set a custom URL for the repository, similar to [ocaml-ci-scripts](https://github.com/ocaml/ocaml-ci-scripts) but without the separation between base remote and branch.
The most awkward part is not being able to set a per-platform default value on the action metadata. I've settled by an empty value by default that gets replaced by the platform default when running the action.
Regarding testing I thought about executing opam after installing, parse the list of repositories and check that the repository is there but …

Add parameter to select default opam repository

---

.gitattributes
lib/install-ocaml-windows.cmd
package.json
src/install-ocaml-windows.cmd

I added 4.11 to a matrix before fdopen had had a chance to update! The log is confusing, because the "Set-up OCaml" step claims to have succeeded (see [this log](https://github.com/metastack/bitmasks/runs/1004270846) from [this run](https://github.com/metastack/bitmasks/actions/runs/215591452) - note that the Unix and macOS ones fail at the "Set-up OCaml 4.12.0" step). Propagating the error in `install-ocaml-windows.cmd` gives the expected result in [this log](https://github.com/metastack/bitmasks/runs/1004252753). I switched it to 4.12 as upstream was actually updated while I was testing the fix.
I also updated `.gitattributes` - normalisation is good, but forcing Unix line-endings is rude (😉) and, at least for batch files, wrong.

Windows fixes

---

lib/install-ocaml-unix.sh
src/install-ocaml-unix.sh

Hi!
I noticed that @smorimoto worked on caching on a separate repo and tried to integrate https://github.com/avsm/hello-world-action-ocaml/blob/with-cache/.github/workflows/workflow.yml in Opium (https://github.com/rgrinberg/opium/pull/183)
Unfortunately, it seems that caching the `~/.opam` directory does not work with multiple compilers at the moment because ocaml-setup uses `opam switch create` even if a switch with the same name already exists.
This PR adds a check that will only create a switch if it does not already exist. The check is really basic, maybe there's a better way to do this with opam?

Check if switch exists before creating

---

CHANGELOG.md
dist/index.js.cache.js
dist/install-ocaml-windows.cmd
src/install-ocaml-windows.cmd
src/installer.ts

I haven't found documentation confirming the exact setup of the DSv2 Windows runners, but while working on a migration to GitHub Actions for OCaml, I discovered that the temporary storage drive (D: - 14GiB) is considerably faster than the system drive.
I tested this on one of my repos where the build itself is mere seconds. Before this change, setup-ocaml needed an average of 5:39 to install OCaml+opam and 1:53 to build the dependencies of the library. After this change, it needs an average of 3:15 for the installation and 1:27 for the deps.

Install Cygwin to the SSD

---

CHANGELOG.md
dist/install-ocaml-unix.sh
src/install-ocaml-unix.sh

The command used to select the switch attempts to select it (caching) and then builds it if not. If the switch isn't there, there's a mildly intimidating error message from opam, before the script carries on to build the switch anyway. There's no need for the message...

Suppress error message if switch doesn't exist

---

CHANGELOG.md
dist/index.js
src/installer.ts

Two changes:
- Cease installing the `ocaml-native-compilers` and `ocaml-compiler-libs` Ubuntu packages. On the runners where the version in Ubuntu (4.05 in 18.04, 4.08 in 20.04) this is a "waste" of time. It's also not brilliant to be randomly using ocaml-system on the package which happens to match. Technically this therefore slows down any 4.05 builds. This is a relatively small adjustment.
- The macOS runners are building OCaml twice - they all build 4.11.1 at `opam init` and then, even on 4.11.1, discard that compiler later on.
`opam init --bare` sets up opam without creating an initial switch... on macOS, this shaves several minutes off the build times.

Speed up the macOS and Ubuntu runners

---

.gitattributes
.github/workflows/workflow.yml

Linting and formatting are important, but it's tedious to lose a run to a mis-formatted line - put the lint checks _after_ actually running the code and always run both of them (technically speaking they'll go haywire if something went wrong installing yarn...)
The `linguist-generated` attribute was pointing to the old `lib` directory.

Two more tiny tweaks

---

CHANGELOG.md
dist/index.js
src/installer.ts

This is a temporary fix that needs to be removed when the problem is resolved, and can be revisited when merging v2.

Run brew update before set up

---

CHANGELOG.md
dist/install-ocaml-windows.sh
src/install-ocaml-windows.sh

This sets a switch variable, not the the global, which is surprising if you run `opam -j 1 install` as `%{jobs}%` is still 3. Given that `OPAMJOBS` is always set in the environment, I don't think there's any need to do this.
(FWIW I think it should have been `opam config set-global jobs`, but as I say I don't think it's needed at all)

Remove opam config set jobs from Windows runner

---

.gitattributes

We accidentally lost the `.gitattributes` in #66!

Restore .gitattributes

---

CHANGELOG.md
dist/LICENSE.txt
dist/post/LICENSE.txt
package.json
src/cache.ts
yarn.lock

This change completely locks cache expiration to one week, but it ensures that compiler packages such as multicore OCaml which directly specify the branch are refreshed weekly. I'm still struggling to decide which side should take this responsibility, the action side or the user side. In fact, this can be addressed in a very similar way by using the cache prefix input. I think `date +%U` actually works well in this case.

Use week number to control opam cache

---

.eslintrc.json
.github/workflows/workflow.yml
CHANGELOG.md
dist/index.js
src/installer.ts

Homebrew now has opam 2.1 which means that the v1 action is failing.
Simplest workaround for now is just to remove the installation of the depext package.

[v1] Fix compatibility on macOS

---

.github/workflows/workflow.yml
CHANGELOG.md
src/cache.ts

This was originally intended to force a weekly reset of the contents of the switch before the multi-repository feature was implemented, but now we remove each repository every time, so we can make this a little loose again.

Make the restore keys of the opam cache loose

---

CHANGELOG.md
src/version.ts

Fixes #262 
Fixes #263 
Fixes #264 
The code is not very sophisticated, but it's fine for now, given that the opam-repository for Windows will be merged relatively soon.

Avoid rate limiting by reducing GitHub API calls

---

CHANGELOG.md
src/constants.ts

It's not technically a bug introduced by us, but it must be fixed anyway.

Return an empty array to avoid depext failure when depext flags are not passed

---

CHANGELOG.md
src/depext.ts
src/dune.ts
src/installer.ts

In opam 2.1 mode, you can still use depext even though you will see a warning. And it turns out that forcing 2.0 mode on the Ubuntu and macOS runners can only ruin the user's workflows, so for now to use 2.1 mode by default.

Use 2.1 mode instead of 2.0 mode on the Ubuntu and macOS runners

---

examples.md

```diff
-      ocaml-repositories: |
+      opam-repositories: |
default: https://github.com/fdopen/opam-repository-mingw.git#opam2
```

correct "ocaml-repositories" to "opam-repositories" in docs

---

CHANGELOG.md
src/setup-ocaml/opam.ts

Cygwin setup 2.912 has a bug in native Windows symlink support and writes some corrupt symlinks; in particular /etc/ssl/certs is corrupt which breaks git and curl.
Depexts will still install using native Windows symlinks, but this should hopefully be less of an issue as the bug affects absolute symlinks, which are less common outside of the base packages.
Issue reported upstream in [this thread](https://cygwin.com/pipermail/cygwin/2022-January/250391.html).

Use --symlink-type=sys for Cygwin setup

---

CHANGELOG.md
lint-fmt/index.js
src/lint-fmt/ocamlformat.ts

print "version not found in .ocamlformat" if the version doesn't exist.
resolve #388

Print a proper error if the version not found in the .ocamlformat file

---

CHANGELOG.md
src/setup-ocaml/dune.ts
src/setup-ocaml/installer.ts

This may break some workflows because the implicitly installed opam-depext will not be installed, but since depext is not often used in workflows where it's disabled, I think this is a reasonable change.
Related: #391

Do not install opam-depext if it's not enabled

---

src/setup-ocaml/opam.ts

CI runners don't need this ownership check - disable it for the Cygwin git installation.
Fixes #479

Turn off git directory ownership check

---

src/setup-ocaml/constants.ts
src/setup-ocaml/system.ts

Hello folks! As part of the effort to get ReScript to [build and run on M1](https://github.com/rescript-lang/rescript-compiler/pull/5415), we are adding a custom M1 runner. Unfortunately this wasn't an architecture that was supported by the `setup-ocaml` action, so here's a small PR to get that allowlisted.
You can see it at work here: https://github.com/rescript-lang/rescript-compiler/runs/6745567808?check_suite_focus=true

feat(arm): do not crash if the platform is arm

---

CHANGELOG.md
src/setup-ocaml/constants.ts

Fail on missing required input instead of warning

---

CHANGELOG.md
src/setup-ocaml/constants.ts
src/setup-ocaml/installer.ts

This env var is supported by some tools to force them to emit ANSI escape sequences corresponding to colors even if they detect that they're not running in tty, which is th case for CI jobs.
It is going to be supported in Dune 3.6.0, and perhaps other compilers and build systems.

Define `CLICOLOR_FORCE=1` env var in CI runs

---

CHANGELOG.md
src/setup-ocaml/opam.ts

The runners have the official Git and Mercurial Windows distributions installed. Avoiding installing the Cygwin packages reduces the cache tarball by roughly 90MB and is more consistent with opam 2.2's internal Cygwin installation (which expects both those packages to be installed externally).

Don't install Cygwin's git or mercurial

---

CHANGELOG.md
src/setup-ocaml/opam.ts

Currently if you add ocaml/opam-repository to the opam-repositories field, e.g.
```
opam-repositories: |
opam-repository-mingw: https://github.com/fdopen/opam-repository-mingw.git
default: https://github.com/ocaml/opam-repository.git
```
The installation of the compiler will fail with:
```
#=== ERROR while compiling ocaml-config.3 =====================================#
Bad hash for D:/.opam/repo/default/packages/ocaml-config/ocaml-config.3/files/gen_ocaml_config.ml.in
```
This is something which is already fixed in opam 2.1 (see https://github.com/ocaml/opam/pull/3882). The proposed fix here works around the problem with the opam 2.0.10 binary from OCaml for Windows.
The problem is that the initial clone of the repository is checked out using Windows line-endings, which causes the hashing …

Allow ocaml/opam-repository to be added to a opam-repositories without hash errors

---

CHANGELOG.md
src/setup-ocaml/constants.ts
src/setup-ocaml/version.ts

[fdopen/opam-repository-mingw](https://github.com/fdopen/opam-repository-mingw) has not been receiving updates since November last year, following its [previously announced deprecation](https://fdopen.github.io/opam-repository-mingw/2021/02/26/repo-discontinued/).
opam 2.2 will add some required additional support for depext support on Windows and we (opam devs) expect to update opam-repository's compiler packages as part of this so that [ocaml/opam-repository](https://github.com/ocaml/opam-repository) can be used without needing opam-repository-mingw, however we're suffering from a slight race condition for the next month or so with existing CI workflows still using fdopen/opam-repository-mingw and wanting to add ocaml/opam-repository in order to get new versions of packages which …

Switch to ocaml-opam/opam-repository-mingw

---

CHANGELOG.md
src/setup-ocaml/opam.ts

#647 reads the output of `git config --global core.autocrlf` in order to restore it afterwards. It wasn't trimming the newline from stdout, so if the workflow _had_ changed the setting then it was restored with a `\n` character at the end which results in a corrupt git configuration.

Trim the output of `git-config`

---

CHANGELOG.md
src/setup-ocaml/cache.ts

Do not try to parse the location as url as it may be a relative filepath, this is a potential fix for #649
Not sure if it's the correct choice for all cases. Another option would be to read the URL from opam once it's been added, or generate it in an ad-hoc way from the relative filepath, then it could be passed to the function and in theory it should work, although you may want to add the u.hash as well to the urn

setup-ocaml/cache: allow creating cache key out of local repos

---

.github/workflows/workflow.yml
CHANGELOG.md
packages/setup-ocaml/src/cache.ts
packages/setup-ocaml/src/opam.ts

As reported in https://github.com/ocaml/opam-repository/issues/23954, `ocamlbuild.0.14.2+win` has been failing to install since last week. This coincides with the release of Cygwin 3.4.7 on 16 June.
The underlying problem is that the Cygwin `tar` package needs to be rebuilt against the new Cygwin DLL which I have [requested upstream](https://cygwin.com/pipermail/cygwin/2023-June/253883.html) (having verified locally that this both fixes the problem and doesn't break Cygwin 3.4.6).
I suggest that we work around this in setup-ocaml in the meantime. This PR:
- Adds an `opam install ocamlbuild` step to CI. This seems useful, given that `ocamlbuild` is a dependency of several core packages and we know it contains symlinks, so it's a non-trivial tarball on Windows
- Updates setup-ocaml to hold …

Hold Cygwin at 3.4.6 to workaround tar issue with Cygwin 3.4.7

---

CHANGELOG.md
packages/setup-ocaml/src/opam.ts

~~Awaiting upstream re-release of tar 1.34 in Cygwin~~
tar [has been updated](https://cygwin.com/pipermail/cygwin/2023-June/253885.html) - the version pin is no longer required.

Remove the pin on Cygwin version

---

CHANGELOG.md
packages/setup-ocaml/src/installer.ts

The hardlink mode is ineffective because two partitions may be used in CI, resulting in EXDEV errors when building.
Fixes #673

Force dune to copy the cache

---

CHANGELOG.md
packages/setup-ocaml/src/constants.ts
packages/setup-ocaml/src/installer.ts

This change should make environment set-up faster for opam 2.2 or later.

Do not install `opam-depext` if using opam 2.2 or later

---

CHANGELOG.md
packages/setup-ocaml/src/installer.ts

Closes https://github.com/ocaml/setup-ocaml/issues/709

Do not set `OPAMCLI` if pre-release opam is allowed

---

CHANGELOG.md
packages/setup-ocaml/src/post.ts

Since the release a few weeks ago, the action runner apparently no longer properly catches the exit of the post process. I don't know the root cause, but we can force exit the post process with `process.exit`.

Force post-process exit with `process.exit`

---

lint-fmt/dist/index.cjs
lint-opam/dist/index.cjs
packages/lint-fmt/src/opam.ts
packages/lint-opam/src/opam.ts

On the assumption it will be updated to opam 2.2...

Do not use the depext subcommand if it's not required

---

dist/post/index.js
packages/setup-ocaml/src/constants.ts

https://github.com/apps/riscv-builders runs on real riscv64 machine
I've tested ocaml 4.11 supported riscv64

Add riscv64 support

---

dist/post/index.js
packages/setup-ocaml/src/constants.ts
packages/setup-ocaml/src/installer.ts

Exporting SHELLOPTS changes the way all shell options behave, so it is better to use BASH_ENV instead. See #920 for more information.
Closes #920.

Set igncr using BASH_ENV instead of SHELLOPTS

---

action.yml

A number of users have been reporting failures on macOS such as:
```
<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><>  🐫 
[default] synchronised from git+https://github.com/ocaml/opam-repository.git
[ERROR] Could not update repository "default": "/opt/homebrew/bin/gpatch -p1 -i /Users/runner/.opam/log/processed-patch-1950-3af777" exited with code 2
```
ever since https://github.com/ocaml/opam-repository/pull/27273 was merged.
Turns out the issue is a GNU Patch bug as it keeps open all the files modified by a given patch file and so it blows up on large patches when `ulimit -n` is too small, which is the case for github actions' macos-latest. It would've been possible to work around it using `ulimit -n` if GNU Patch had done a patch release in the last 7 years …

Work around failures on platforms where the number of files open at once is limited

---

dist/post/index.js
packages/setup-ocaml/src/cache.ts

This is useful under fairly unusual but high-impact race conditions...

Do not create cache if cache already exists

---

dist/LICENSE.txt
dist/post/LICENSE.txt
dist/post/index.js
packages/setup-ocaml/package.json
packages/setup-ocaml/src/dune.ts
packages/setup-ocaml/src/opam.ts
packages/setup-ocaml/src/version.ts
yarn.lock

Closes https://github.com/ocaml/setup-ocaml/issues/943

Add @octokit/plugin-retry to improve API call reliability

---

dist/post/index.js
packages/setup-ocaml/src/cache.ts
packages/setup-ocaml/src/constants.ts
packages/setup-ocaml/src/installer.ts
packages/setup-ocaml/src/opam.ts
packages/setup-ocaml/src/version.ts
packages/setup-ocaml/src/windows.ts

Closes https://github.com/ocaml/setup-ocaml/issues/943

Don't make heavy API requests multiple times

---

packages/setup-ocaml/src/windows.ts

`3.0.16-1` has finally been marked as stable and released, so maybe we can just drop them?
https://cygwin.com/packages/summary/mingw64-x86_64-openssl-src.html

Remove pinned OpenSSL packages from Cygwin setup step

---

dist/post/index.js
packages/setup-ocaml/src/cache.ts

Fix cache restoration logic to use `Promise.allSettled` for better error handling

---

dist/post/index.js
packages/setup-ocaml/src/constants.ts
packages/setup-ocaml/src/unix.ts

Fixes https://github.com/ocaml/setup-ocaml/pull/940#issuecomment-2741820444

Fix package installation logic for the self-hosted runner environment

---

packages/setup-ocaml/src/installer.ts
packages/setup-ocaml/src/windows.ts

Patch fstab on Cygwin temporarily

---

.github/workflows/workflow.yml
packages/setup-ocaml/src/unix.ts

GitHub allows running actions in containers [1] on the runners, and when
using a non apt-based Linux distribution, setup-ocaml doesn't work
correctly. This commit skips package management on docker containers,
similar to the behavior on self-hosted runners.
[1]: https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container

Skip package management if running in github-hosted container

---

action.yml
dist/post/index.cjs
packages/setup-ocaml/src/constants.ts

Switch Cygwin installation from `D:` to `C:` drive due to `D:` drive removal in Windows Server 2025 runners. While this may impact performance compared to the previous `D:` drive optimization (PR #55), it ensures compatibility with the new runner environment.
Closes #990

Fix Cygwin installation path for Windows Server 2025
